[package]
name = "qoa"
version = "0.2.6"
edition = "2021"

# see more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
num-complex = { version = "0.4", features = ["serde"] }
rand = "0.8.5"
rand_distr = "0.4.3"
log = "0.4.21"
env_logger = "0.11.3"
image = "0.25.1"
duct = "0.13.6"
hound = "3.5.1"
ndarray = "0.15.6"
realfft = "3.5.0"
rustfft = "6.4.0"
rayon = "1.10"
indicatif = { version = "0.17", features = ["rayon"] }
rand_chacha = "0.3.1"

# OPTIMIZATIONS: ONLY USE FOR RELEASE!!!

# [profile.release]
# opt-level = 3
# lto = "fat"
# codegen-units = 1
# panic = "abort"
# strip = "debuginfo"
# debug = false # DISABLE IF DEBUGGING!

# [build]
# rustflags = ["-C", "target-cpu=native"]