[package]
name = "qoa"
version = "0.2.0"
edition = "2021"

[dependencies]
num-bigint = "0.4"
num-traits = "0.2"
rand = "0.8"
rand_distr = "0.4"
num-complex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4", features = ["derive"] }