[build]
# general rustflags applied to all targets unless overridden
rustflags = [
    # use free software optimizations that work across architectures
    "-C", "llvm-args=-vectorize-loops",
    "-C", "llvm-args=-vectorize-slp", 
    "-C", "llvm-args=-enable-gvn-hoist"
]

[profile.dev]
# development profile settings
opt-level = 1
debug = true

[profile.release]
# release profile settings for optimization
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[profile.release.build-override]
# override settings for build dependencies in release mode
opt-level = 3
codegen-units = 1

# target-specific settings for x86_64 architecture
[target.'cfg(target_arch = "x86_64")']
rustflags = [
    "-C", "target-cpu=native",
    # use free software vectorization optimizations
    "-C", "llvm-args=-vectorize-loops",
    "-C", "llvm-args=-vectorize-slp",
    "-C", "llvm-args=-enable-gvn-hoist"
]

# cross-compilation settings for arm64 (aarch64)
[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
rustflags = [
    "-C", "target-cpu=generic",  # use generic arm64 optimizations
    "-C", "llvm-args=-vectorize-loops",
    "-C", "llvm-args=-vectorize-slp",
    # use static linking to avoid library compatibility issues
    "-C", "target-feature=+crt-static"
]

# cross-compilation settings for risc-v 64-bit
[target.riscv64gc-unknown-linux-gnu]
linker = "riscv64-linux-gnu-gcc"
rustflags = [
    "-C", "target-cpu=generic-rv64",  # generic risc-v 64-bit
    "-C", "llvm-args=-vectorize-loops",
    "-C", "llvm-args=-vectorize-slp"
]

# cross-compilation settings for powerpc 64-bit little endian
[target.powerpc64le-unknown-linux-gnu]
linker = "powerpc64le-linux-gnu-gcc"
rustflags = [
    "-C", "target-cpu=generic",  # use generic powerpc optimizations
    "-C", "llvm-args=-vectorize-loops",
    "-C", "llvm-args=-vectorize-slp"
]

# environment variables for cross-compilation
[env]
# force vendored openssl for cross-compilation
OPENSSL_STATIC = "1"
OPENSSL_VENDORED = "1"
PKG_CONFIG_ALLOW_CROSS = "1"

# arm64 cross-compilation environment
CC_aarch64_unknown_linux_gnu = "aarch64-linux-gnu-gcc"
CXX_aarch64_unknown_linux_gnu = "aarch64-linux-gnu-g++"
AR_aarch64_unknown_linux_gnu = "aarch64-linux-gnu-ar"
FC_aarch64_unknown_linux_gnu = "aarch64-linux-gnu-gfortran"

# risc-v cross-compilation environment  
CC_riscv64gc_unknown_linux_gnu = "riscv64-linux-gnu-gcc"
CXX_riscv64gc_unknown_linux_gnu = "riscv64-linux-gnu-g++"
AR_riscv64gc_unknown_linux_gnu = "riscv64-linux-gnu-ar"

# powerpc cross-compilation environment
CC_powerpc64le_unknown_linux_gnu = "powerpc64le-linux-gnu-gcc" 
CXX_powerpc64le_unknown_linux_gnu = "powerpc64le-linux-gnu-g++"
AR_powerpc64le_unknown_linux_gnu = "powerpc64le-linux-gnu-ar"

# use system math libraries instead of intel-specific ones
LIBM_STATIC = "true"
# force use of gnu toolchain components
FORCE_GNU_TOOLCHAIN = "true"
